name: Kingactyl
icon: https://cdn.discordapp.com/attachments/998170574843035720/1003467646769057882/unknown.png
defaulttheme: default
version: 1.0.0
website:
  port: 80
  secret: Example Secret

discordserver:
  enabled: true
  invitelink: https://discord.gg/example

ads:
  enabled: false
  script: ''

guildblacklist:
  guilds:
  - ServerID
  - ServerID

pterodactyl:
  domain: https://panel.example.com/
  key: ptla_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

storelimits:
  ram: 8192
  disk: 16384
  cpu: 400
  databases: 4
  allocations: 4
  backups: 4

# AFK Party dosent work currently.
AFK Party: 
  enabled: false
  webhook: ""
  users: 1
  multiplier: 2	

linkvertise:
  enabled: true
  userid: 390178
  coins: 25

status:
  enabled: true
  url: https://example.com

stripe:
  enabled: true  
  key: 0000000000 # Replace this with your Stripe API Key
  coins: 200 # Coins per amount in USD
  amount: 1

smtp:
  enabled: false
  host: Example Host
  port: 7080
  username: Example Username
  password: Example Password

api:
  server:
    enabled: true
    key: API KEY
  client:
    j4r: 
      enabled: true
      ads:
      - name: Example Server 1
        id: 000000000000000000
        invite: https://discord.gg/example
        coins: 50
      - name: Example Server 2
        id: 933803406513012807
        invite: https://discord.gg/example
        coins: 50

    Role Packages:
      enabled: false
      Server: SERVERID # Replace SERVERID with your Guild/Server ID
      list: # Replace ROLEID with the Role ID, you can add as many as you want.
        RoleID: Package Name 

    bot:
      token: ""
      joinguild:
        enabled: false
        guildid:
        - SERVERID
        - SERVERID
        forcejoin: false
        registeredrole: ""

    webhook:
      webhook_url: ""
      auditlogs:
        enabled: true
        disabled: []

    passwordgenerator:
      signup: true # Use this to disable signups
      length: 8

    allow:
      gift: true
      newusers: true
      regen: true
      server:
        create: true
        modify: true
        delete: true

    oauth2: # Discord OAUTH2
      id: ""
      secret: ""
      link: "https://client.example.com"
      callbackpath: "/callback"
      prompt: true
    
    ip:
      trust x-forwarded-for: true
      block: []
      duplicate check: false

    packages:
      default: default
      list:
        default:
          ram: 2048
          disk: 5192
          cpu: 100
          servers: 1
          databases: 2
          allocations: 2
          backups: 2

    locations:
      '1':
        name: Example Location
        package: null
   
    eggs:
      paper:
        display: Minecraft Java (Paper)
        minimum:
          ram: 512
          disk: 512
          cpu: 25
        maximum:
          ram: 8000
          disk: 16000
          cpu: 400
        info:
          egg: 15
          docker_image: ghcr.io/pterodactyl/yolks:java_17
          startup: java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar {{SERVER_JARFILE}}
          environment:
            MINECRAFT_VERSION: "latest"
            SERVER_JARFILE: "server.jar"
            DL_PATH: ""
            BUILD_NUMBER: "latest"
          feature_limits:
            databases: 2
            backups: 2

    coins:
      enabled: true
      store:
        enabled: true
        ram:
          cost: 100
          per: 1
        disk:
          cost: 100
          per: 1
        cpu:
          cost: 100
          per: 1
        servers:
          cost: 100
          per: 1
        databases:
          cost: 100
          per: 1
        ports:
          cost: 100
          per: 1
        backups:
          cost: 100
          per: 1

  minero:
    enabled: false
    key: Minero Public Key

#afk page is not available currently

  arcio:
    enabled: true 
    widgetid: VmfQD6oE # only change this if you have your own widget id
    afk page:
      enabled: true
      path: afkwspath
      every: 10
      coins: 1
      coinlimit: 50 # Daily coin limit, set to 0 if you want to disable it.

whitelist:
  enabled: false
  users:
    - Email Address

nologin:
  enabled: true # Suspends and Deletes servers if the user doesn't login for amount of days.
  days: 7

servercreation:
  cost: 0

renewal: 
  enabled: false
  cost: 200
  delay: 3 

AntiVPN:
  enabled: false
  key: KEY
  whitelistedIPs:
    - IP Address

widget:
  enabled: false
  server_id: GUILD_ID
  channel_Id: CHANNEL_ID
